In [ ]:
# 내장함수 예 : input
strText = input("아무 문장이나 입력하세요 : ")
print(strText)

아무 문장이나 입력하세요 : 테스트
테스트


In [ ]:
# List를 이용한 다차원 배열
flVal = [1.0, 2.0, 3.14, 4.2, 5.1]  # 실수 list를 생성

In [ ]:
# flVal 3개를 리스트로 구성하여 arVal 다차원 배열을 생성
arVal = [flVal, flVal, flVal]
arVal

[[1.0, 2.0, 3.14, 4.2, 5.1],
 [1.0, 2.0, 3.14, 4.2, 5.1],
 [1.0, 2.0, 3.14, 4.2, 5.1]]

In [ ]:
# arVal은 다차원 배열이므로, arVal[n] 인덱스 연산을 통해 n차원 배열 값을 출력
arVal[0]

[1.0, 2.0, 3.14, 4.2, 5.1]

In [ ]:
arVal[1]

[1.0, 2.0, 3.14, 4.2, 5.1]

In [ ]:
arVal[1][2]

3.14

In [ ]:
# 1 차원 값을 변환하여 다른 값을 대입 했을때의 다차원 배열
arVal[0] = 'python'
arVal

['python', [1.0, 2.0, 3.14, 4.2, 5.1], [1.0, 2.0, 3.14, 4.2, 5.1]]

In [ ]:
arVal[0][2]

't'

In [ ]:
arVal[0] = 'python programming'
arVal

['python programming', [1.0, 2.0, 3.14, 4.2, 5.1], [1.0, 2.0, 3.14, 4.2, 5.1]]

In [ ]:
# numpy 패치지를 import 
import numpy as np
arData = np.array([1.0, 2.0, 3.14, 4.2, 5.1])
arData

array([1.  , 2.  , 3.14, 4.2 , 5.1 ])

In [ ]:
# 배열 각 요소의 합을 출력
arData.sum()

15.44

In [ ]:
arVal.sum()

AttributeError: ignored

In [ ]:
print(type(arVal))
print(type(arData))

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
# 배열에 대한 표준편차 출력
arData.std()

1.4717934637713266

In [ ]:
# 배열의 누적 합을 출력
arData.cumsum()

array([ 1.  ,  3.  ,  6.14, 10.34, 15.44])

In [ ]:
arData * 2

array([ 2.  ,  4.  ,  6.28,  8.4 , 10.2 ])

In [ ]:
arData ** 2 # 2를 제곱

array([ 1.    ,  4.    ,  9.8596, 17.64  , 26.01  ])

In [ ]:
# 루트를 적용한 값을 출력
np.sqrt(arData)

array([1.        , 1.41421356, 1.77200451, 2.04939015, 2.25831796])

In [ ]:
arVal = np.array([arData, arData ** 2])
arVal

array([[ 1.    ,  2.    ,  3.14  ,  4.2   ,  5.1   ],
       [ 1.    ,  4.    ,  9.8596, 17.64  , 26.01  ]])

In [ ]:
arVal.sum(axis=0) # 축(axis)이 0일 경우 세로 축의 합을 출력

array([ 2.    ,  6.    , 12.9996, 21.84  , 31.11  ])

In [ ]:
arVal.sum(axis=1) # 축(axis)이 0일 경우 가로 축의 합을 출력

array([15.44  , 58.5096])

In [ ]:
# NumPy.array를 사용한 코드
np.array([[0,0,0],[0,0,0]])

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
# NumPy.zeros를 사용한 코드
arZero = np.zeros((2,3), dtype = 'i') 
arZero

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [ ]:
# pandas import
import pandas as pd

pandas_series = pd.Series([30, 20, 10], index=['국어', '영어', '수학'])
print(type(pandas_series))
pandas_series

<class 'pandas.core.series.Series'>


국어    30
영어    20
수학    10
dtype: int64

In [ ]:
pandas_series[1:]

영어    20
수학    10
dtype: int64

In [ ]:
pandas_series[0]

30

In [ ]:
pandas_series[0][1]

IndexError: ignored

In [ ]:
df = pd.DataFrame([30,20,10], columns=['score'], index=['국어', '영어', '수학'])
df

score
국어     30
영어     20
수학     10

In [ ]:
# DataFrame의 index를 표시
df.index

Index(['국어', '영어', '수학'], dtype='object')

In [ ]:
# DataFrame의 column을 표시
df.columns

Index(['score'], dtype='object')

In [ ]:
# DataFrame의index 중에서 국어에 해당하는 값을 출력
df.loc['국어']   # ix 함수가 최근 제거되어 loc를 써야 동작

score    30
Name: 국어, dtype: int64

In [ ]:
# DataFrame의 값을 모두 합한 결과를 출력
df.sum()

score    60
dtype: int64

In [ ]:
# DataFrame의 각 colimn 값의 제곱을 출력
df.score ** 2

국어    900
영어    400
수학    100
Name: score, dtype: int64

In [ ]:
# DataFrame에 score2 라는 칼럼을 추가하고 값을 입력
df['score2'] = (50, 50, 50)
df

score  score2
국어     30      50
영어     20      50
수학     10      50

In [ ]:
# DataFrame 함수를 이용하여 column을 추가할 수 있음
df['score2'] = pd.DataFrame([90,90,90], index=['국어', '영어', '수학'])
df

score  score2
국어     30      90
영어     20      90
수학     10      90

In [ ]:
# column 삭제
del df['score']

In [ ]:
# index 를 맞추기 않았을 경우
df['score2'] = (90, 90, 90, 100)

ValueError: ignored

In [ ]:
# index 를 맞추기 않았을 경우
df['score2'] = pd.DataFrame([90, 90, 90, 100], index=['국어', '영어', '수학', '윤리'])
df

score  score2
국어     30      90
영어     20      90
수학     10      90

In [ ]:
# join() 함수를 이용하여 2개의 DataFrame을 하나로 합칠 수 있음
df1 = pd.DataFrame([1, 2, 3], columns = ['A'])
df2 = pd.DataFrame([10, 11, 12, 13], columns = ['B'])

df = df1.join(df2, how='outer')
df

A   B
0  1.0  10
1  2.0  11
2  3.0  12
3  NaN  13

In [ ]:
df_inner = df1.join(df2, how='inner')
df_inner

A   B
0  1  10
1  2  11
2  3  12

In [ ]:
# 난수를 이용한 임의의 값 생성
df = pd.DataFrame(np.random.randn(5,5))
df.columns = ['A', 'B', 'C', 'D', 'E']

df

A         B         C         D         E
0  0.543405 -0.847763  0.681296 -0.093539  0.952255
1 -1.153325  0.120657  0.505057  0.614817  0.624625
2 -2.378809  1.702129 -0.838859  0.903119 -0.270950
3 -2.370525  1.028808 -0.503830  1.054736  0.271516
4 -0.425577 -0.499254  2.448141  0.545844  0.563218

In [ ]:
# 최대값
df.max()

A    0.543405
B    1.702129
C    2.448141
D    1.054736
E    0.952255
dtype: float64

In [ ]:
# 최소값
df.min()

A   -2.378809
B   -0.847763
C   -0.838859
D   -0.093539
E   -0.270950
dtype: float64

In [ ]:
# 평균
df.mean()

A   -1.156966
B    0.300915
C    0.458361
D    0.604995
E    0.428133
dtype: float64

In [ ]:
# 표준편차
df.std()

A    1.264103
B    1.058944
C    1.286438
D    0.442349
E    0.459567
dtype: float64

In [ ]:
# 누적값
df.cumsum()

A         B         C         D         E
0  0.543405 -0.847763  0.681296 -0.093539  0.952255
1 -0.609920 -0.727106  1.186354  0.521278  1.576880
2 -2.988729  0.975023  0.347494  1.424397  1.305930
3 -5.359254  2.003831 -0.156335  2.479133  1.577446
4 -5.784831  1.504576  2.291805  3.024976  2.140664

In [ ]:
# DataFrame의 통계적 요약
df.describe()

A         B         C         D         E
count  5.000000  5.000000  5.000000  5.000000  5.000000
mean  -1.156966  0.300915  0.458361  0.604995  0.428133
std    1.264103  1.058944  1.286438  0.442349  0.459567
min   -2.378809 -0.847763 -0.838859 -0.093539 -0.270950
25%   -2.370525 -0.499254 -0.503830  0.545844  0.271516
50%   -1.153325  0.120657  0.505057  0.614817  0.563218
75%   -0.425577  1.028808  0.681296  0.903119  0.624625
max    0.543405  1.702129  2.448141  1.054736  0.952255

In [ ]:
# Group by를 이용한 DataFrame의 그룹화
df['division'] = ['X', 'Y', 'X', 'Y', 'Z']
df

A         B         C         D         E division
0  0.543405 -0.847763  0.681296 -0.093539  0.952255        X
1 -1.153325  0.120657  0.505057  0.614817  0.624625        Y
2 -2.378809  1.702129 -0.838859  0.903119 -0.270950        X
3 -2.370525  1.028808 -0.503830  1.054736  0.271516        Y
4 -0.425577 -0.499254  2.448141  0.545844  0.563218        Z

In [ ]:
df.groupby(['division']).mean()

A         B         C         D         E
division                                                  
X        -0.917702  0.427183 -0.078781  0.404790  0.340652
Y        -1.761925  0.574732  0.000614  0.834776  0.448070
Z        -0.425577 -0.499254  2.448141  0.545844  0.563218